name: Integração Contínua

on:
  pull_request:
    branches:
      - main
  push:

jobs:
  executa_isort:
    runs-on: ubuntu-latest
    steps:
      - name: Realiza o checkout
        uses: actions/checkout@v3
    
      - name: Instala o Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: instala o poetry
        uses: Gr1N/setup-poetry@v7
        
      - name: Instala as dependências
        run: poetry install
        
      - name: Executa o isort
        run: poetry run isort --check *
        
  executa_pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Realiza o checkout
        uses: actions/checkout@v3
    
      - name: Instala o Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: instala o poetry
        uses: Gr1N/setup-poetry@v7
        
      - name: Instala as dependências
        run: poetry install
        
      - name: Executa os testes unitários
        run: poetry run pytest
        
        
  executa_safety:
    runs-on: ubuntu-latest
    steps:
      - name: Realiza o checkout
        uses: actions/checkout@v3
    
      - name: Instala o Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: instala o poetry
        uses: Gr1N/setup-poetry@v7
        
      - name: Instala as dependências
        run: poetry install
        
      - name: Executando o safety
        run: poetry run safety check